### ISSUE TITLE
Error in replace function

### ISSUE THREAD

**Issue by marceljay** [aspiers/linear-analysis#11]
Showed up after trying to create a graph:

```
└─$ yarn linear graph --project "Celo Retirements" --svg my-project.svg     1 ⨯

yarn run v1.22.19
$ bin/linear graph --project 'Celo Retirements' --svg my-project.svg
Found project 'Celo Retirements' with id e3c126f3-f085-4757-acdd-11e078166eaf
Doing issue query page 1 at start ...
  Got 50 new node(s); total now 50; hasNextPage=true
Doing issue query page 2 after 863d5910-a11c-4e63-94ba-61376ff240a2 ...
  Got 16 new node(s); total now 66; hasNextPage=false
dev/linear-analysis/src/commands/graph.ts:368
    .replaceAll('&', '&amp;')
     ^
TypeError: s.replaceAll is not a function
    at encode (dev/linear-analysis/src/commands/graph.ts:368:6)
    at getNodeAttrs (dev/linear-analysis/src/commands/graph.ts:401:21)
    at createNode (dev/linear-analysis/src/commands/graph.ts:338:21)
    at registerNode (dev/linear-analysis/src/commands/graph.ts:358:32)
    at buildGraph (dev/linear-analysis/src/commands/graph.ts:517:5)
    at Command.run (dev/linear-analysis/src/commands/graph.ts:708:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by aspiers** [comment]
I think you're using an old node.js.  Please try `nvm use stable`.

**Comment by aspiers** [comment]
This worked.  Updated README in 3d7152ea1cb843462237b5f92189f9f99c3d54c0.
